[en]
  languageName = "English"
  contentDir = "content/en"
  weight = 15
  [en.params]
    languageISO = "EN"
[kor]
  languageName = "Korean"
  contentDir = "content/kor"
  weight = 10
  [kor.params]
    languageISO = "KOR"
