name: CI for github pages

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "17"

      - name: Install dependencies
        run: npm ci

      - name: Run test script
        run: npm test
