name: "Automation] Pull Request"
on:
  pull_request:
    types: [opened, synchronize, edited, reopened, closed]

jobs:
  assign-reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: reviewers
        uses: hkusu/review-assign-action@v1
        with:
          assignees: ${{ github.actor }}
          reviewers: Aiden-Jeon, anencore94, zamonia500
          max-num-of-reviewers: 2
          draft-keyword: WIP  # A keyword in the pull request title to treat as draft pull requests
          ready-comment: 'Ready for review :rocket: <reviewers>'

  size-label:
    runs-on: ubuntu-latest
    steps:
      - name: size-label
        uses: pascalgn/size-label-action@v0.4.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IGNORED: "**/package-lock.json\n**/package.json"
        with:
          sizes: >
            {
              "0": "XS",
              "25": "S",
              "120": "M",
              "300": "L",
              "1000": "XL",
              "3000": "XXL",
              "10000": "XXXL"
            }
