name: "Pull Request"
on:
  pull_request:
    types: [opened, synchronize, edited, reopened, closed]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: anencore94/labeler@v1.1.0

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pre-commit/action@v2.0.0
